version: '2'

services:
    w2agrid:
        image: selenium/hub:2.53.1
        container_name: w2agrid
        privileged: true
        ports:
            - 4446:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - w2agrid_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug:2.53.1
        privileged: true
        depends_on:
            - w2agrid
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - HUB_PORT_4444_TCP_ADDR=w2agrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - w2agrid_grid_internal

    nodefirefox:
        image: selenium/node-firefox-debug:2.53.1
        privileged: true
        depends_on:
            - w2agrid
        ports:
            - 5901  
        environment:
            - no_proxy=localhost
            - HUB_PORT_4444_TCP_ADDR=w2agrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - w2agrid_grid_internal

networks:
    w2agrid_grid_internal: